title: Parins-Fukuchi Lab at U of T
email: c.parinsfukuchi@utoronto.ca
description: Computational Evolutionary Biology 
twitter_username: carolinetomo
github_username: carolinetomo

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - people.md
  - papers.md
  - projects.md
  - software.md
