title: Fukuchi Lab at U of T
email: c.parinsfukuchi@utoronto.ca
description: Computation and Evolution at U. Toronto EEB

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - people.md
  - papers.md
  - projects.md
  - software.md
